### ISSUE TITLE
seq2seq实现

### ISSUE THREAD

**Issue by wjj5881005** [Coder-Liuu/TopoMAD#1]
您好，请问GraphLSTMDecoder的实现中，为什么解码器不使用编码器最后一个时间戳输出的h，
reconst_h, _ = self.graph_lstm_cell.get_init()
        for xt in torch.flip(x[:-1], dims=[0]):
            xxt = xt if focing else reconst_mu.view(self.batch_size, self.nodes, -1)
            reconst_h, c = self.graph_lstm_cell(xxt, reconst_h, c)

上面的reconst_h使用的是 self.graph_lstm_cell.get_init()函数得到的初始化的h，不是应该跟c一样使用编码器中最后一层的输出么？

**Comment by Coder-Liuu** [comment]
确实是使用的编码器中最后一层的输出，不过我代码有些时间没有看了。:dizzy_face:

**Comment by Coder-Liuu** [comment]
> 您好，请问GraphLSTMDecoder的实现中，为什么解码器不使用编码器最后一个时间戳输出的h，
> reconst_h, _ = self.graph_lstm_cell.get_init()
> for xt in torch.flip(x[:-1], dims=[0]):
> xxt = xt if focing else reconst_mu.view(self.batch_size, self.nodes, -1)
> reconst_h, c = self.graph_lstm_cell(xxt, reconst_h, c)
> 
> 上面的reconst_h使用的是 self.graph_lstm_cell.get_init()函数得到的初始化的h，不是应该跟c一样使用编码器中最后一层的输出么？

确实是使用的编码器中最后一层的输出，不过我代码有些时间没有看了。😵

**Comment by Coder-Liuu** [comment]
> 不是应该跟c一样使用编码器中最后一层的输出么

你好，先说答案，h**不应该**跟c一样使用编码器最后一层的输出的。

我重新看了一下代码，文章中的initialize state这条线是输出编码器的最后一层的c，但是**编码器最后一层的h是经过q(z_t|X_{t-W+1:t})**，也就是经过一次变分自编码之后才来作为解码器的输入的，所以解码器的h应该是初始的h。

![image](https://user-images.githubusercontent.com/46812648/130718406-efbaea5e-f4d7-4381-9adb-df5fb27f1fc3.png)
